include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    invalid_assignment: warning
    dead_code: info
    todo: ignore
    missing_required_param: error
    missing_return: error
    unawaited_futures: warning
    unused_import: warning
    invalid_annotation_target: ignore
 
  exclude:
    - "**.g.dart"
    - "**.freezed.dart"
    - "**.config.dart"
    - "**.chopper.dart"
    - "**.mocks.dart"
    - lib/app/generated/**.dart
    - lib/app/generated/**
    - lib/**/generated_plugin_registrant.dart
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    # Better readability
    always_specify_types: true
    unsafe_html: true 
    prefer_expression_function_bodies: true

    #Suppressed Lints
    public_member_api_docs: false
    flutter_style_todos: false
    one_member_abstracts: false
    omit_local_variable_types: false
    avoid_classes_with_only_static_members: false
    lines_longer_than_80_chars: false
 

