name: shared
description: A shared Flutter package project.
version: 0.0.1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  animations: ^2.0.7
  bloc: ^8.1.2
  cached_network_image: ^3.2.3
  chopper: ^7.0.4
  connectivity_plus: ^4.0.2
  dartx: ^1.2.0
  flash: ^3.0.5
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.6
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  flutter_web_plugins:
    sdk: flutter
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  go_router: ^8.2.0
  http: ^1.1.0
  intl: ^0.18.1
  intl_utils: ^2.8.4
  json_annotation: ^4.8.1
  logger: ^2.0.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.0

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  chopper_generator: ^7.0.2
  dependency_validator: ^3.2.2
  flutter_gen: ^5.3.1
  flutter_gen_runner: ^5.3.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  mockito: ^5.4.2
  very_good_analysis: ^5.0.0+1

flutter_gen:
  output: lib/app/generated/
  integration:
    flutter_svg: true

flutter_intl:
  enabled: true
  class_name: SharedLocalizations
  arb_dir: assets/l10n/
  output_dir: lib/app/generated/

flutter:
  uses-material-design: true
  assets:
    - assets/images/
