name: simpsons

on: [pull_request, push]

jobs:
  verify-semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    runs-on: "ubuntu-latest"

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v3

      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-$

      - name: 📦 Install Dependencies
        run: |
          flutter pub global activate very_good_cli
          very_good --analytics false
          very_good packages get --recursive
      - name: ⚙️ Run Setup
        run: |
          flutter pub run intl_utils:generate
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: ✨ Check Formatting
        run: dart format --set-exit-if-changed lib test

      - name: 🕵️ Analyze
        run: |
          flutter analyze lib test
          dart analyze lib test

      - name: 🧪 Run Tests
        run: flutter test --dart-define=CI=true --coverage
        
      - name: 📤 Upload Failed Goldens
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: goldens-failures
          path: test/widget/**/failures

      - name: 📊 Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: ./coverage/lcov.info
          exclude: "lib/app/config/* lib/app/utils/* lib/app/generated/* lib/app/generated/intl/* lib/app/themes/* lib/bootstrap.dart *.g.dart  *.freezed.dart *.dto.dart *.config.dart *.chopper.dart **/*_webview.dart **/service/* **/model/*"
          min_coverage: 80