include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    invalid_assignment: warning
    dead_code: info
    todo: ignore
    missing_required_param: error
    missing_return: error
    unawaited_futures: warning
    unused_import: warning
    invalid_annotation_target: ignore
 
  exclude:
    - "**.g.dart"
    - "**.freezed.dart"
    - "**.config.dart"
    - "**.chopper.dart"
    - "**.mocks.dart"
    - lib/app/generated/**.dart
    - lib/app/generated/**
    - lib/**/generated_plugin_registrant.dart
  plugins:
    - dart_code_metrics
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    # Better readability
    always_specify_types: true
    unsafe_html: true 
    prefer_expression_function_bodies: true

    #Suppressed Lints
    public_member_api_docs: false
    flutter_style_todos: false
    one_member_abstracts: false
    omit_local_variable_types: false
    avoid_classes_with_only_static_members: false
    lines_longer_than_80_chars: false
 

dart_code_metrics:
  anti-patterns:
    - long-method:
        severity: warning
        exclude:
          - test/**
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 10
    lines-of-code: 70
    maintainability-index: 60
    maximum-nesting-level: 4
    number-of-methods: 7
    number-of-parameters: 4
    source-lines-of-code: 40
    weight-of-class: 0.33

  technical-debt:
      threshold: 1
      todo-cost: 3
      ignore-cost: 2
      ignore-for-file-cost: 4
      as-dynamic-cost: 1
      deprecated-annotations-cost: 4
      file-nullsafety-migration-cost: 5
      unit-type: "MD"

  metrics-exclude:
    - "**.g.dart"
    - "**.freezed.dart"
    - "**.config.dart"
    - "**.chopper.dart"
    - "**.mocks.dart"
    - lib/app/generated/**.dart
    - lib/app/generated/**
    - lib/**/generated_plugin_registrant.dart

  rules:
    # Commons
    - avoid-cascade-after-if-null
    - avoid-collection-methods-with-unrelated-types
    - avoid-double-slash-imports
    - avoid-duplicate-exports
    - avoid-global-state
    - avoid-missing-enum-constant-in-map
    - avoid-nested-conditional-expressions:
        acceptable-level: 3
    - avoid-redundant-async:
        severity: info
    - avoid-top-level-members-in-tests:
        exclude:
          - test/utils/**
          - test/flutter_test_config.dart    
    - avoid-unnecessary-conditionals
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters
    - binary-expression-operand-order
    - double-literal-format:
        exclude:
          - test/**
    - list-all-equatable-fields
    - member-ordering-extended:
        order:
          - constructors
          - named-constructor
          - factory-constructor
          - static-public-fields
          - static-private-fields
          - fields
          - methods
        widgets-order:
          - constructor
          - named-constructor
          - fields
          - methods
          - build-method
          - dispose-method
    - missing-test-assertion:
        include-assertions:
          - verify
          - verifyNever
          - verifyInOrder    
    - no-boolean-literal-compare
    - no-empty-block:
        exclude:
          - test/**
    - no-equal-then-else
    - no-object-declaration
    - prefer-async-await
    - prefer-conditional-expressions
    - prefer-correct-identifier-length:
        min-identifier-length: 3
        max-identifier-length: 30 
    - prefer-correct-test-file-name:
        severity: warning     
    - prefer-correct-type-name:
        min-length: 3
        max-length: 40
    - prefer-first 
    - prefer-immediate-return
    - prefer-iterable-of
    - prefer-last
    - prefer-match-file-name:
        severity: warning
        exclude:
          - test/**
          - "**.dto.dart"   
    - prefer-moving-to-variable      
    - prefer-static-class:
        ignore-private: true
        exclude:
          - test/** 
    # Flutter       
    - tag-name:
        exclude:
          - test/**
    - always-remove-listener      
    - avoid-expanded-as-spacer
    - avoid-returning-widgets:
        severity: warning
    - avoid-shrink-wrap-in-lists
    - avoid-unnecessary-setstate
    - use-setstate-synchronously
    - avoid-wrapping-in-padding
    - check-for-equals-in-render-object-setters
    - consistent-update-render-object         
    - prefer-correct-edge-insets-constructor
    - prefer-extracting-callbacks:
        allowed-line-count: 0
        ignored-named-arguments:
          - listener
          - listenWhen
          - buildWhen
          - itemBuilder
          - builder
    - prefer-single-widget-per-file:
        ignore-private-widgets: true
    - prefer-using-list-view
    - use-setstate-synchronously
    # Intl
    - prefer-intl-name
    - provide-correct-intl-args

