name: the_wire
description: A Very Good App
version: 1.0.0+1
publish_to: none

environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  chopper: ^7.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.0
  go_router: ^8.2.0
  http: ^1.1.0
  injectable: ^2.3.0
  intl: ^0.18.1
  intl_utils: ^2.8.4
  logger: ^2.0.1
  pretty_chopper_logger: ^1.0.7
  responsive_framework: ^0.2.0
  shared: ^0.0.1

dev_dependencies:
  build_runner: ^2.4.6
  chopper_generator: ^7.0.2
  dependency_validator: ^3.2.2
  flutter_gen: ^5.3.1
  flutter_gen_runner: ^5.3.1
  injectable_generator: ^2.4.0
  very_good_analysis: ^5.0.0+1


flutter_gen:
  output: lib/app/generated/
  integration:
    flutter_svg: true

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  arb_dir: assets/l10n/
  output_dir: lib/app/generated/

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/env/
